using NUnit.Framework;using OpenQA.Selenium;using OpenQA.Selenium.Support.UI;using SeleniumExtras.WaitHelpers;namespace ReqnrollMarsAutomationProject.Pages{    public class SkillsPage    {        private readonly IWebDriver _driver;        private readonly WebDriverWait _wait;        public IWebDriver Driver => _driver;        // Locators               private readonly By SkillsTab = By.XPath("//*[@id=\"account-profile-section\"]/div/section[2]/div/div/div/div[3]/form/div[1]/a[2]");        private readonly By SkillsAddNewButton = By.XPath("//*[@id=\"account-profile-section\"]/div/section[2]/div/div/div/div[3]/form/div[3]/div/div[2]/div/table/thead/tr/th[3]/div");        private readonly By AddSkillText = By.Name("name");        private readonly By ChooseSkillLevel = By.XPath("//select[@name='level']");        private readonly By AddSkillButton = By.XPath("//*[@id=\"account-profile-section\"]/div/section[2]/div/div/div/div[3]/form/div[3]/div/div[2]/div/div/span/input[1]");        private readonly By SkillInTableRow = By.XPath("//table[@class='ui fixed table']/tbody[last()]/tr/td[1]");        private readonly By SkillLevelInTableRow = By.XPath("//div[@data-tab='second']/div/div[2]/div/table[@class='ui fixed table']/tbody[last()]/tr/td[2]");        private readonly By UpdateButton = By.XPath("//input[@value='Update']");        private readonly By DeleteSkill = By.XPath("//i[contains(@class,\"remove\")]");        private readonly By popupmsg = By.XPath("//div[@class='ns-box-inner']");
        private readonly By DeleteSkills = By.XPath("//table[@class='ui fixed table']/tbody/tr/td[1]/following-sibling :: td[2]/span/i[@class='remove icon']");

        public SkillsPage(IWebDriver driver) // Inject IWebDriver directly        {            _driver = driver;            _wait = new WebDriverWait(_driver, TimeSpan.FromSeconds(10)); // 10-second timeout        }                public void AddSkills(string SkillName, string SkillLevel)        {            var SkillsAddNewButtonElement = _wait.Until(ExpectedConditions.ElementToBeClickable(SkillsAddNewButton));            SkillsAddNewButtonElement.Click();            var AddSkillElement = _wait.Until(ExpectedConditions.ElementIsVisible(AddSkillText));            AddSkillElement.SendKeys(SkillName);            var ChooseSkillLevelElement = _wait.Until(ExpectedConditions.ElementIsVisible(ChooseSkillLevel));            ChooseSkillLevelElement.Click();            var selectElement = new SelectElement(ChooseSkillLevelElement);            selectElement.SelectByValue(SkillLevel);            var AddSkillButtonElement = _wait.Until(ExpectedConditions.ElementToBeClickable(AddSkillButton));            AddSkillButtonElement.Click();            Thread.Sleep(2000);        }            

        public void SkillsAndLevelVerification(string SkillName, string SkillLevel, out String ActualSkillName, out String ActualSkillLevel, out String ActualPopup)        {            var popupmsgActual = _wait.Until(d => d.FindElement(popupmsg)).Text;            var SkillInTable = _wait.Until(d => d.FindElement(SkillInTableRow)).Text;            var SkillLevelInTable = _wait.Until(d => d.FindElement(SkillLevelInTableRow)).Text;            ActualSkillName = SkillInTable;            ActualSkillLevel = SkillLevelInTable;            ActualPopup = popupmsgActual;
        }

        
        public void VerifyAlreadyExistSkillPopup(out String ActualPopup)        {            var popupmsgActual = _wait.Until(d => d.FindElement(popupmsg)).Text;            ActualPopup = popupmsgActual;                        
        }        public void VerifyDuplicateSkillPopup(out String ActualPopup)        {            var popupmsgActual = _wait.Until(d => d.FindElement(popupmsg)).Text;            ActualPopup = popupmsgActual;                   }

               public void VerifyEmptySkillAndLevePopup(out String ActualPopup)        {            var popupmsgActual = _wait.Until(d => d.FindElement(popupmsg)).Text;            ActualPopup = popupmsgActual;
            
        }        public void DeleteSkillFromTable(String skill, String level)        {            try            {                Thread.Sleep(5000);                IWebElement DeleteElementForAddedSkill = _wait.Until(ExpectedConditions.ElementIsVisible(By.XPath($"//td[text()='{skill}']")));                var deleteSkillElementForAddedSkill = _wait.Until(ExpectedConditions.ElementToBeClickable(DeleteSkill));                deleteSkillElementForAddedSkill.Click();                Console.WriteLine("Skill deleted successfully.");            }            catch (WebDriverTimeoutException)            {                Assert.Fail("Failed to delete skill from the table.");            }        }               public void VerifyDeletedSkillFromTable(String skill, out String ActualPopup)        {            var popupmsgActual = _wait.Until(d => d.FindElement(popupmsg)).Text;            ActualPopup = popupmsgActual;
                                   
        }        public void verfiyEditSkillAndLevel(String skill, String level, String updatedSkill, String updatedLevel)        {            try            {                IWebElement EditElementForAddedSkill = _wait.Until(ExpectedConditions.ElementIsVisible(By.XPath($"//td[text()='{skill}']/following-sibling::td[2]/span/i[contains(@class,'outline')]")));                var editSkillElementForAddedSkill = _wait.Until(ExpectedConditions.ElementToBeClickable(EditElementForAddedSkill));                editSkillElementForAddedSkill.Click();                var AddSkillElement = _wait.Until(ExpectedConditions.ElementIsVisible(AddSkillText));                AddSkillElement.Clear(); // Clear the existing text before sending new text                AddSkillElement.SendKeys(updatedSkill);                var ChooseSkillLevelElement = _wait.Until(ExpectedConditions.ElementIsVisible(ChooseSkillLevel));                ChooseSkillLevelElement.Click();                var selectElement = new SelectElement(ChooseSkillLevelElement);                selectElement.SelectByValue(updatedLevel);                var UpdateButtonElement = _wait.Until(ExpectedConditions.ElementToBeClickable(UpdateButton));                UpdateButtonElement.Click();                Console.WriteLine("Skill edited successfully.");            }            catch (WebDriverTimeoutException)            {                Assert.Fail("Failed to delete skill from the table.");            }        }        public void verifyUpdateSkillAndLevel(String skill, String level)        {            try            {                String xpath = $"//div[text()='{skill} has been updated to your skills']";                IWebElement SkillUpdatePopup = _wait.Until(ExpectedConditions.ElementIsVisible(By.XPath(xpath)));                Assert.That(SkillUpdatePopup.Displayed, "Update Skill popup should be displayed");                Console.WriteLine("Empty skill and level popup is displayed: " + SkillUpdatePopup.Text);                var SkillInTable = _wait.Until(d => d.FindElement(SkillInTableRow)).Text;                Assert.That(SkillInTable, Is.EqualTo(skill), "Updated skill should be present in the table");                var DeleteSkillElement = _wait.Until(ExpectedConditions.ElementToBeClickable(DeleteSkill));                DeleteSkillElement.Click();            }            catch (Exception e)            {                Assert.Fail("Failed to verify Updated skill from the table." + e);            }        }
        public void ClearData()
        {
            try
            {
                var deleteButtons = _driver.FindElements(DeleteSkills);
                foreach (var button in deleteButtons)
                {
                    button.Click();
                    Thread.Sleep(1000); // Wait for the deletion to process
                }
                Console.WriteLine("All languages deleted successfully.");
            }
            catch (Exception e)
            {
                Assert.Fail("Failed to clear data: " + e);
            }
        }    }}